## 데이터 Augmentation 정답데이터 만드는 법

### 1. 원본데이터 로드

In [1]:
import pandas as pd


import os

# D drive
data_path = 'D:\dataset\Dacon\dirty_mnist/'

data = pd.read_csv(data_path + 'dirty_mnist_2nd_answer.csv')
print(data.shape)
data.head()

(50000, 27)

   index  a  b  c  d  e  f  g  h  i  ...  q  r  s  t  u  v  w  x  y  z
0      0  1  1  0  1  0  1  0  0  0  ...  0  1  1  0  1  0  0  1  1  1
1      1  1  0  0  1  0  1  0  1  0  ...  0  1  0  1  0  0  0  0  1  1
2      2  0  0  0  0  0  0  0  0  1  ...  0  0  1  1  1  0  1  1  1  0
3      3  0  0  1  0  0  0  1  1  0  ...  1  0  1  1  0  1  1  0  1  0
4      4  0  1  0  1  0  1  0  1  1  ...  0  1  0  0  0  1  0  1  0  0

[5 rows x 27 columns]

### 2. 데이터 이어붙이기
- Pandas dataframe append()

In [2]:
# 원본 + 90도 rotation (== 270도 rotation)
data2 = data.append(data)
print(data2.shape)

data3 = data.append(data).append(data)
print(data3.shape)

(100000, 27)
(150000, 27)

## 3. index 기준 정렬 및 to_csv

In [7]:
data2 = data2.sort_values(by='index')
data2.to_csv('dirty_mnist_2nd_answer_90_or_270.csv', index=False)

data3 = data3.sort_values(by='index')
data3.to_csv('dirty_mnist_2nd_answer_90_and_270.csv', index=False)

print('to_csv완료')

to_csv완료

## 4. 데이터 확인

In [8]:
check1 = pd.read_csv('dirty_mnist_2nd_answer_90_or_270.csv')
print(check1.shape)
check1.head(10)

(100000, 27)

   index  a  b  c  d  e  f  g  h  i  ...  q  r  s  t  u  v  w  x  y  z
0      0  1  1  0  1  0  1  0  0  0  ...  0  1  1  0  1  0  0  1  1  1
1      0  1  1  0  1  0  1  0  0  0  ...  0  1  1  0  1  0  0  1  1  1
2      1  1  0  0  1  0  1  0  1  0  ...  0  1  0  1  0  0  0  0  1  1
3      1  1  0  0  1  0  1  0  1  0  ...  0  1  0  1  0  0  0  0  1  1
4      2  0  0  0  0  0  0  0  0  1  ...  0  0  1  1  1  0  1  1  1  0
5      2  0  0  0  0  0  0  0  0  1  ...  0  0  1  1  1  0  1  1  1  0
6      3  0  0  1  0  0  0  1  1  0  ...  1  0  1  1  0  1  1  0  1  0
7      3  0  0  1  0  0  0  1  1  0  ...  1  0  1  1  0  1  1  0  1  0
8      4  0  1  0  1  0  1  0  1  1  ...  0  1  0  0  0  1  0  1  0  0
9      4  0  1  0  1  0  1  0  1  1  ...  0  1  0  0  0  1  0  1  0  0

[10 rows x 27 columns]

In [9]:
check2 = pd.read_csv('dirty_mnist_2nd_answer_90_and_270.csv')
print(check2.shape)
check2.head(10)

(150000, 27)

   index  a  b  c  d  e  f  g  h  i  ...  q  r  s  t  u  v  w  x  y  z
0      0  1  1  0  1  0  1  0  0  0  ...  0  1  1  0  1  0  0  1  1  1
1      0  1  1  0  1  0  1  0  0  0  ...  0  1  1  0  1  0  0  1  1  1
2      0  1  1  0  1  0  1  0  0  0  ...  0  1  1  0  1  0  0  1  1  1
3      1  1  0  0  1  0  1  0  1  0  ...  0  1  0  1  0  0  0  0  1  1
4      1  1  0  0  1  0  1  0  1  0  ...  0  1  0  1  0  0  0  0  1  1
5      1  1  0  0  1  0  1  0  1  0  ...  0  1  0  1  0  0  0  0  1  1
6      2  0  0  0  0  0  0  0  0  1  ...  0  0  1  1  1  0  1  1  1  0
7      2  0  0  0  0  0  0  0  0  1  ...  0  0  1  1  1  0  1  1  1  0
8      2  0  0  0  0  0  0  0  0  1  ...  0  0  1  1  1  0  1  1  1  0
9      3  0  0  1  0  0  0  1  1  0  ...  1  0  1  1  0  1  1  0  1  0

[10 rows x 27 columns]